driver:
   name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  enforce_idempotency: true
  multiple_converge: 2
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: amazonlinux-2
    drive_config:
      box: stakahashi/amazonlinux2
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-latest
  - name: opensuse-leap-15
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
    - recipe[test::default]
  # - name: ssl
  #   run_list:
  #   - recipe[test::mod_ssl]
